export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_DISMISS = 'ADD_CATEGORY_DISMISS';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const ADD_CARD = 'ADD_CARD';
export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_DISMISS = 'ADD_CARD_DISMISS';
export const MARK_COMPETE_CARD = 'MARK_COMPETE_CARD';
export const GET_CARDS = 'GET_CARDS';
export const DELETE_CARD = 'DELETE_CARD';
export const CARD_MARK_COMPLETE = 'CARD_MARK_COMPLETE';
export const CARD_MARK_INCOMPLETE = 'CARD_MARK_COMPLETE';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_ERROR = 'GET_CARDS_ERROR';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const VISIBILITY_FILTERS = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_INCOMPLETE: 'SHOW_INCOMPLETE'
};